/**
 * generateProReportPDF
 *
 * Generates a multi-page A4 PDF "Pro Report" from the user's builder selections.
 * Uses jsPDF for layout — no canvas required (data-driven, not DOM-captured).
 *
 * Structure:
 *   Page 1 — Cover: Before / After comparison + brand header
 *   Page 2 — Materials Specification
 *   Page 3 — Detailed Cost Breakdown + Project Brief
 */

import { jsPDF } from "jspdf";
import type { BuilderSelections } from "./types";
import type { ProjectBrief } from "./projectBrief";
import { calcBriefCostItems, needsAsbestosCheck } from "./projectBrief";
import { buildItemisedCosts, calcEstimatedCost, getBathroomBaseCost, VANITY_OPTIONS, TAPWARE_OPTIONS } from "./types";
import { formatAUD } from "./utils";

interface ProReportInput {
  selections:        BuilderSelections;
  projectBrief:      ProjectBrief | null;
  generatedImageUrl: string | null;
  roomPhotoUrl:      string | null;
  grandTotal:        number;
  estimatedCost:     number;
}

// ── Brand constants ──────────────────────────────────────────────────────────
const CHARCOAL   = [44,  62,  80]  as [number, number, number];
const TERRACOTTA = [210, 125, 94]  as [number, number, number];
const SAND       = [245, 240, 232] as [number, number, number];
const WHITE      = [255, 255, 255] as [number, number, number];
const GREY_TEXT  = [120, 130, 140] as [number, number, number];
const AMBER      = [217, 119, 6]   as [number, number, number];

// ── Helpers ──────────────────────────────────────────────────────────────────

function setFont(pdf: jsPDF, weight: "bold" | "normal" = "normal") {
  pdf.setFont("helvetica", weight);
}

function hex3(r: number, g: number, b: number): string {
  return `#${[r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}

function drawRect(
  pdf: jsPDF,
  x: number, y: number, w: number, h: number,
  fill: [number, number, number],
  radius = 0,
) {
  pdf.setFillColor(...fill);
  if (radius > 0) {
    pdf.roundedRect(x, y, w, h, radius, radius, "F");
  } else {
    pdf.rect(x, y, w, h, "F");
  }
}

function addHeader(pdf: jsPDF, pageWidth: number, title: string, pageNum: number, totalPages: number) {
  // Header band
  drawRect(pdf, 0, 0, pageWidth, 18, CHARCOAL);
  setFont(pdf, "bold");
  pdf.setTextColor(...WHITE);
  pdf.setFontSize(9);
  pdf.text("RENO READY", 12, 11.5);
  pdf.setFontSize(7);
  setFont(pdf, "normal");
  pdf.setTextColor(...[255, 255, 255, 0.5] as unknown as [number, number, number]);
  pdf.text(title.toUpperCase(), pageWidth / 2, 11.5, { align: "center" });
  pdf.setTextColor(...WHITE);
  pdf.text(`${pageNum} / ${totalPages}`, pageWidth - 12, 11.5, { align: "right" });
}

function addFooter(pdf: jsPDF, pageWidth: number, pageHeight: number) {
  pdf.setFontSize(6.5);
  setFont(pdf, "normal");
  pdf.setTextColor(...GREY_TEXT);
  pdf.text(
    "Generated by Reno Ready · reno-ready.com.au · Estimates based on Australian market rates 2026. All figures inc. GST.",
    pageWidth / 2, pageHeight - 6, { align: "center" }
  );
}

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    if (url.startsWith("data:")) return url;
    const res  = await fetch(url);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror  = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function generateProReportPDF(input: ProReportInput): Promise<void> {
  const { selections, projectBrief, generatedImageUrl, roomPhotoUrl, grandTotal, estimatedCost } = input;

  const pdf       = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW        = pdf.internal.pageSize.getWidth();   // 210mm
  const PH        = pdf.internal.pageSize.getHeight();  // 297mm
  const MARGIN    = 14;
  const INNER_W   = PW - MARGIN * 2;
  const TOTAL_PGS = 3;

  const vanityLabel  = VANITY_OPTIONS.find((v) => v.id === selections.vanity)?.label  ?? selections.vanity;
  const tapwareLabel = TAPWARE_OPTIONS.find((t) => t.id === selections.tapware)?.label ?? selections.tapware;

  // Pre-load images
  const [aiImageData, roomImageData] = await Promise.all([
    generatedImageUrl ? loadImageAsDataUrl(generatedImageUrl) : Promise.resolve(null),
    roomPhotoUrl      ? loadImageAsDataUrl(roomPhotoUrl)      : Promise.resolve(null),
  ]);

  // ══════════════════════════════════════════════════════════════════
  //  PAGE 1 — Cover: Before / After
  // ══════════════════════════════════════════════════════════════════
  addHeader(pdf, PW, "Project Preview Report", 1, TOTAL_PGS);

  let y = 24;

  // Brand accent stripe
  drawRect(pdf, MARGIN, y, 4, 8, TERRACOTTA, 2);
  setFont(pdf, "bold");
  pdf.setTextColor(...CHARCOAL);
  pdf.setFontSize(16);
  pdf.text("Your Bathroom Design Preview", MARGIN + 8, y + 6);
  y += 14;

  const dateStr = new Date().toLocaleDateString("en-AU", { year: "numeric", month: "long", day: "numeric" });
  setFont(pdf, "normal");
  pdf.setFontSize(8);
  pdf.setTextColor(...GREY_TEXT);
  pdf.text(`Prepared ${dateStr} · Reno Ready AI Design Platform`, MARGIN + 8, y);
  y += 10;

  // Before / After images side-by-side
  const imgH = 72;
  const imgW = (INNER_W - 6) / 2;

  if (roomImageData) {
    // "Before" panel
    drawRect(pdf, MARGIN, y, imgW, imgH, SAND, 4);
    pdf.addImage(roomImageData, "JPEG", MARGIN, y, imgW, imgH);
    // Label
    drawRect(pdf, MARGIN, y + imgH - 8, imgW, 8, [...CHARCOAL, 0.75] as unknown as [number, number, number]);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...WHITE);
    pdf.text("CURRENT STATE", MARGIN + imgW / 2, y + imgH - 3.5, { align: "center" });
  } else {
    drawRect(pdf, MARGIN, y, imgW, imgH, SAND, 4);
    setFont(pdf, "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...GREY_TEXT);
    pdf.text("No room photo uploaded", MARGIN + imgW / 2, y + imgH / 2, { align: "center" });
    setFont(pdf, "bold");
    pdf.text("CURRENT STATE", MARGIN + imgW / 2, y + imgH - 3.5, { align: "center" });
  }

  if (aiImageData) {
    const rx = MARGIN + imgW + 6;
    pdf.addImage(aiImageData, "JPEG", rx, y, imgW, imgH);
    // Terracotta label
    drawRect(pdf, rx, y + imgH - 8, imgW, 8, TERRACOTTA, 0);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...WHITE);
    pdf.text("AI FUTURE VISION", rx + imgW / 2, y + imgH - 3.5, { align: "center" });
  } else {
    const rx = MARGIN + imgW + 6;
    drawRect(pdf, rx, y, imgW, imgH, [230, 220, 210] as [number, number, number], 4);
    setFont(pdf, "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...GREY_TEXT);
    pdf.text("Generate an AI preview first", rx + imgW / 2, y + imgH / 2, { align: "center" });
  }

  y += imgH + 8;

  // Cost hero card
  drawRect(pdf, MARGIN, y, INNER_W, 26, CHARCOAL, 4);
  setFont(pdf, "bold");
  pdf.setFontSize(8);
  pdf.setTextColor(...[255, 255, 255, 0.5] as unknown as [number, number, number]);
  pdf.setTextColor(180, 190, 200);
  pdf.text("ESTIMATED ALL-IN COST", MARGIN + 8, y + 8);
  pdf.setFontSize(20);
  pdf.setTextColor(...WHITE);
  pdf.text(formatAUD(projectBrief ? grandTotal : estimatedCost), MARGIN + 8, y + 20);
  setFont(pdf, "normal");
  pdf.setFontSize(7.5);
  pdf.setTextColor(180, 190, 200);
  pdf.text("Based on Australian market rates 2026 · Inc. GST · ±12% typical variance", PW - MARGIN - 2, y + 20, { align: "right" });

  y += 34;

  // Selections summary grid (4 chips)
  const chips = [
    { label: "Floor Tile",   value: selections.floorTile?.name ?? "Not selected" },
    { label: "Wall Tile",    value: selections.wallTile?.name  ?? "Not selected" },
    { label: "Vanity",       value: vanityLabel                                   },
    { label: "Tapware",      value: tapwareLabel                                  },
  ];
  const chipW = (INNER_W - 6) / 4;
  chips.forEach((chip, i) => {
    const cx = MARGIN + i * (chipW + 2);
    drawRect(pdf, cx, y, chipW, 16, SAND, 3);
    setFont(pdf, "bold");
    pdf.setFontSize(6.5);
    pdf.setTextColor(...TERRACOTTA);
    pdf.text(chip.label.toUpperCase(), cx + chipW / 2, y + 5.5, { align: "center" });
    setFont(pdf, "normal");
    pdf.setFontSize(7.5);
    pdf.setTextColor(...CHARCOAL);
    const truncated = chip.value.length > 18 ? chip.value.slice(0, 17) + "…" : chip.value;
    pdf.text(truncated, cx + chipW / 2, y + 12, { align: "center" });
  });

  y += 24;

  // Structural changes summary (if any)
  const sc = selections.structuralChanges;
  const scChanges: string[] = [];
  if (sc?.removeBathtub)   scChanges.push("Bathtub removal");
  if (sc?.addWalkinShower) scChanges.push("Walk-in shower addition");
  if (sc?.replaceToilet)   scChanges.push("Toilet replacement");
  if (sc?.inWallCistern)   scChanges.push("In-wall cistern");
  if (sc?.showerNiche === "single") scChanges.push("Single shower niche");
  if (sc?.showerNiche === "double") scChanges.push("Double shower niche");
  if (sc?.showerFixtures === "dual") scChanges.push("Dual shower fixtures");

  if (scChanges.length > 0) {
    drawRect(pdf, MARGIN, y, INNER_W, 6 + scChanges.length * 5.5, [244, 240, 234] as [number, number, number], 3);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...CHARCOAL);
    pdf.text("STRUCTURAL CHANGES", MARGIN + 4, y + 5);
    setFont(pdf, "normal");
    pdf.setFontSize(7.5);
    scChanges.forEach((ch, i) => {
      pdf.setTextColor(...CHARCOAL);
      pdf.text(`· ${ch}`, MARGIN + 4, y + 10 + i * 5.5);
    });
    y += 8 + scChanges.length * 5.5;
  }

  addFooter(pdf, PW, PH);

  // ══════════════════════════════════════════════════════════════════
  //  PAGE 2 — Materials Specification
  // ══════════════════════════════════════════════════════════════════
  pdf.addPage();
  addHeader(pdf, PW, "Materials Specification", 2, TOTAL_PGS);
  y = 24;

  // Title
  drawRect(pdf, MARGIN, y, 4, 8, TERRACOTTA, 2);
  setFont(pdf, "bold");
  pdf.setFontSize(14);
  pdf.setTextColor(...CHARCOAL);
  pdf.text("Materials & Specification", MARGIN + 8, y + 6);
  y += 16;

  // Materials table
  const matRows: { label: string; spec: string; note?: string }[] = [
    { label: "Floor Tile",    spec: selections.floorTile?.name  ?? "Not selected", note: selections.customFloorColor ?? undefined },
    { label: "Wall Tile",     spec: selections.wallTile?.name   ?? "Not selected", note: selections.customWallColor  ?? undefined },
    { label: "Vanity Type",   spec: vanityLabel },
    { label: "Tapware Finish",spec: tapwareLabel },
    ...(selections.tileStyle ? [{ label: "Tile Pattern", spec: selections.tileStyle as string }] : []),
    ...(selections.lightingOption && selections.lightingOption !== "none" && selections.lightingOption !== "standard"
      ? [{ label: "Lighting Upgrade", spec: selections.lightingOption as string }]
      : []),
  ];

  const rowH = 11;
  matRows.forEach((row, i) => {
    const rowY = y + i * rowH;
    drawRect(pdf, MARGIN, rowY, INNER_W, rowH, i % 2 === 0 ? WHITE : SAND);
    setFont(pdf, "bold");
    pdf.setFontSize(7.5);
    pdf.setTextColor(...GREY_TEXT);
    pdf.text(row.label.toUpperCase(), MARGIN + 4, rowY + 7);
    setFont(pdf, "normal");
    pdf.setFontSize(8.5);
    pdf.setTextColor(...CHARCOAL);
    pdf.text(row.spec, MARGIN + 60, rowY + 7);
    if (row.note) {
      pdf.setFontSize(7);
      pdf.setTextColor(...TERRACOTTA);
      pdf.text(`Custom colour: ${row.note}`, MARGIN + 60, rowY + 11);
    }
  });

  y += matRows.length * rowH + 8;

  // Custom note (if any)
  if (selections.customNote?.trim()) {
    drawRect(pdf, MARGIN, y, INNER_W, 18, [250, 245, 240] as [number, number, number], 3);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...TERRACOTTA);
    pdf.text("ADDITIONAL CLIENT REQUEST", MARGIN + 4, y + 6);
    setFont(pdf, "normal");
    pdf.setFontSize(8.5);
    pdf.setTextColor(...CHARCOAL);
    const noteLines = pdf.splitTextToSize(`"${selections.customNote.trim()}"`, INNER_W - 8);
    noteLines.slice(0, 2).forEach((line: string, li: number) => {
      pdf.text(line, MARGIN + 4, y + 12 + li * 5);
    });
    y += 26;
  }

  // Hygiene advisory (if single bathroom)
  if (projectBrief?.bathroomCount === 1) {
    y += 4;
    drawRect(pdf, MARGIN, y, INNER_W, 28, [255, 251, 235] as [number, number, number], 3);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...AMBER);
    pdf.text("⚠  SINGLE BATHROOM — HYGIENE ADVISORY", MARGIN + 4, y + 6);
    setFont(pdf, "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...CHARCOAL);
    const hygieneText = pdf.splitTextToSize(
      "This is the only bathroom in the home. Most clients arrange a Mobile Ensuite (self-contained trailer) for $150–$300/week during the 2–4 week build window. Confirm toilet/shower access with your builder before works commence.",
      INNER_W - 8,
    );
    hygieneText.slice(0, 3).forEach((line: string, li: number) => {
      pdf.text(line, MARGIN + 4, y + 12 + li * 5);
    });
    y += 36;
  }

  addFooter(pdf, PW, PH);

  // ══════════════════════════════════════════════════════════════════
  //  PAGE 3 — Cost Breakdown
  // ══════════════════════════════════════════════════════════════════
  pdf.addPage();
  addHeader(pdf, PW, "Detailed Cost Breakdown", 3, TOTAL_PGS);
  y = 24;

  drawRect(pdf, MARGIN, y, 4, 8, TERRACOTTA, 2);
  setFont(pdf, "bold");
  pdf.setFontSize(14);
  pdf.setTextColor(...CHARCOAL);
  pdf.text("Detailed Cost Breakdown", MARGIN + 8, y + 6);
  y += 16;

  // Column headers
  const labelX = MARGIN + 4;
  const amtX   = PW - MARGIN - 2;
  drawRect(pdf, MARGIN, y, INNER_W, 7, CHARCOAL);
  setFont(pdf, "bold");
  pdf.setFontSize(7);
  pdf.setTextColor(...WHITE);
  pdf.text("ITEM", labelX, y + 5);
  pdf.text("AMOUNT (INC. GST)", amtX, y + 5, { align: "right" });
  y += 7;

  // Base renovation items
  const baseCost    = getBathroomBaseCost(selections.bathroomSize, selections.customLength, selections.customWidth);
  const baseItems   = buildItemisedCosts(
    selections.floorTile, selections.wallTile, selections.vanity,
    selections.tapware, selections.structuralChanges, baseCost
  );

  const itemRowH = 9;
  baseItems.forEach((item, i) => {
    const rowY = y + i * itemRowH;
    drawRect(pdf, MARGIN, rowY, INNER_W, itemRowH, i % 2 === 0 ? WHITE : SAND);
    setFont(pdf, "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...CHARCOAL);
    pdf.text(item.label, labelX, rowY + 6);
    setFont(pdf, "bold");
    const amtStr = item.amount > 0 ? `+${formatAUD(item.amount)}` : item.amount < 0 ? formatAUD(item.amount) : "Included";
    pdf.text(amtStr, amtX, rowY + 6, { align: "right" });
  });
  y += baseItems.length * itemRowH + 2;

  // Brief items (verified costs)
  const briefItems = projectBrief ? calcBriefCostItems(projectBrief) : [];
  if (briefItems.length > 0) {
    drawRect(pdf, MARGIN, y, INNER_W, 7, [240, 235, 228] as [number, number, number]);
    setFont(pdf, "bold");
    pdf.setFontSize(6.5);
    pdf.setTextColor(...GREY_TEXT);
    pdf.text("VERIFIED COST ITEMS · SOURCED FROM REAL AUSTRALIAN INVOICES", labelX, y + 5);
    y += 7;

    briefItems.forEach((item, i) => {
      const rowY = y + i * itemRowH;
      drawRect(pdf, MARGIN, rowY, INNER_W, itemRowH, i % 2 === 0 ? WHITE : [255, 251, 235] as [number, number, number]);
      setFont(pdf, "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(item.warning ? AMBER[0] : CHARCOAL[0], item.warning ? AMBER[1] : CHARCOAL[1], item.warning ? AMBER[2] : CHARCOAL[2]);
      const prefix = item.warning ? "⚠  " : "";
      pdf.text(`${prefix}${item.label}`, labelX, rowY + 6);
      if (item.source) {
        setFont(pdf, "normal");
        pdf.setFontSize(6.5);
        pdf.setTextColor(...GREY_TEXT);
        pdf.text(item.source, labelX, rowY + 8.5);
      }
      setFont(pdf, "bold");
      pdf.setFontSize(8);
      pdf.setTextColor(item.warning ? AMBER[0] : CHARCOAL[0], item.warning ? AMBER[1] : CHARCOAL[1], item.warning ? AMBER[2] : CHARCOAL[2]);
      pdf.text(`+${formatAUD(item.amount)}`, amtX, rowY + 6, { align: "right" });
    });
    y += briefItems.length * itemRowH + 2;
  }

  // Grand total row
  const total = projectBrief ? grandTotal : estimatedCost;
  drawRect(pdf, MARGIN, y, INNER_W, 12, CHARCOAL, 3);
  setFont(pdf, "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(...WHITE);
  pdf.text("ALL-IN ESTIMATED TOTAL", labelX, y + 8);
  pdf.text(formatAUD(Math.round(total / 500) * 500), amtX, y + 8, { align: "right" });
  y += 16;

  // Variance note
  setFont(pdf, "normal");
  pdf.setFontSize(7.5);
  pdf.setTextColor(...GREY_TEXT);
  pdf.text(`Typical range: ${formatAUD(Math.round(total * 0.88 / 500) * 500)} – ${formatAUD(Math.round(total * 1.12 / 500) * 500)}  (±12%)`, labelX, y);
  y += 10;

  // Project Brief summary box (if populated)
  if (projectBrief) {
    drawRect(pdf, MARGIN, y, INNER_W, 32, SAND, 4);
    setFont(pdf, "bold");
    pdf.setFontSize(7);
    pdf.setTextColor(...TERRACOTTA);
    pdf.text("PROJECT BRIEF", labelX, y + 7);
    setFont(pdf, "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...CHARCOAL);
    const briefLines = [
      `Year of Construction: ${projectBrief.yearBuilt}`,
      `Renovation Scope: ${projectBrief.scope === "full-stripout" ? "Full Strip-out" : "Cosmetic Refresh"}`,
      `Plumbing: ${projectBrief.plumbingLayout === "keep-layout" ? "Keep Existing Layout" : "Moving Plumbing / Walls"}`,
      `Bathrooms: ${projectBrief.bathroomCount === 3 ? "3 or more" : String(projectBrief.bathroomCount)}${projectBrief.bathroomCount === 1 ? " (sole bathroom)" : ""}`,
      ...(needsAsbestosCheck(projectBrief) ? ["⚠  Asbestos risk flagged — testing & removal included in estimate"] : []),
    ];
    briefLines.forEach((line, li) => {
      pdf.text(line, labelX, y + 13 + li * 5);
    });
  }

  addFooter(pdf, PW, PH);

  // ── Save ─────────────────────────────────────────────────────────────────────
  pdf.save("Reno-Ready-Pro-Report.pdf");
}
