/**
 * generateProReportPDF
 *
 * Generates a 2-page A4 "Pro Report" PDF that is fully room-aware.
 * Kitchen, bedroom, and bathroom each get their own materials spec and
 * correct itemised cost breakdown.
 *
 * Structure:
 *   Page 1 — Cover: Before/After · Cost Hero · Materials Specification
 *   Page 2 — Full Itemised Cost Breakdown · Project Brief
 */

import { jsPDF } from "jspdf";
import type { BuilderSelections } from "./types";
import type { ProjectBrief } from "./projectBrief";
import type { RoomType, KitchenSelections, BedroomSelections } from "./roomTypes";
import { calcBriefCostItems, needsAsbestosCheck, calcBriefTotal } from "./projectBrief";
import { buildItemisedCosts, calcEstimatedCost, getBathroomBaseCost, VANITY_OPTIONS, TAPWARE_OPTIONS } from "./types";
import {
  calcKitchenCost, calcBedroomCost,
  CABINETRY_OPTIONS, BENCHTOP_OPTIONS, SPLASHBACK_OPTIONS, MIXER_OPTIONS,
  CEILING_OPTIONS, KITCHEN_SIZE_OPTIONS, BEDROOM_SIZE_OPTIONS,
  BEDROOM_FLOORING_OPTIONS, WALL_TREATMENT_OPTIONS, BEDROOM_LIGHTING_OPTIONS,
  STORAGE_OPTIONS, WINDOW_TREATMENT_OPTIONS,
} from "./roomTypes";
import { formatAUD } from "./utils";

// ── Input ────────────────────────────────────────────────────────────────────

export interface ProReportInput {
  selections:        BuilderSelections;
  projectBrief:      ProjectBrief | null;
  generatedImageUrl: string | null;
  roomPhotoUrl:      string | null;
  grandTotal:        number;
  estimatedCost:     number;
  // Room-specific
  roomType:          RoomType;
  kitchenSelections: KitchenSelections | null;
  bedroomSelections: BedroomSelections | null;
}

// ── Brand constants ──────────────────────────────────────────────────────────

const CHARCOAL   = [44,  62,  80]  as [number, number, number];
const TERRACOTTA = [210, 125, 94]  as [number, number, number];
const SAND       = [245, 240, 232] as [number, number, number];
const WHITE      = [255, 255, 255] as [number, number, number];
const GREY_TEXT  = [120, 130, 140] as [number, number, number];
const AMBER      = [217, 119, 6]   as [number, number, number];
const LIGHT_SAND = [250, 246, 241] as [number, number, number];

// ── Helpers ──────────────────────────────────────────────────────────────────

function sf(pdf: jsPDF, weight: "bold" | "normal" = "normal") {
  pdf.setFont("helvetica", weight);
}

function drawRect(
  pdf: jsPDF,
  x: number, y: number, w: number, h: number,
  fill: [number, number, number],
  radius = 0,
) {
  pdf.setFillColor(...fill);
  if (radius > 0) pdf.roundedRect(x, y, w, h, radius, radius, "F");
  else            pdf.rect(x, y, w, h, "F");
}

function addHeader(pdf: jsPDF, PW: number, title: string, pageNum: number) {
  drawRect(pdf, 0, 0, PW, 18, CHARCOAL);
  sf(pdf, "bold");
  pdf.setTextColor(...WHITE);
  pdf.setFontSize(9);
  pdf.text("RENO READY", 12, 11.5);
  pdf.setFontSize(7);
  sf(pdf, "normal");
  pdf.setTextColor(180, 190, 200);
  pdf.text(title.toUpperCase(), PW / 2, 11.5, { align: "center" });
  pdf.setTextColor(...WHITE);
  pdf.text(`${pageNum} / 2`, PW - 12, 11.5, { align: "right" });
}

function addFooter(pdf: jsPDF, PW: number, PH: number) {
  pdf.setFontSize(6.5);
  sf(pdf, "normal");
  pdf.setTextColor(...GREY_TEXT);
  pdf.text(
    "Generated by Reno Ready · renoready.com.au · Estimates indicative only · QLD 2026 market rates · All figures inc. GST · ±12% typical variance",
    PW / 2, PH - 5.5, { align: "center" }
  );
}

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    if (url.startsWith("data:")) return url;
    const res  = await fetch(url);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror  = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch { return null; }
}

// ── Room label helper ────────────────────────────────────────────────────────

function roomLabel(rt: RoomType) {
  return rt === "kitchen" ? "Kitchen" : rt === "bedroom" ? "Bedroom" : "Bathroom";
}

// ── Build material rows (room-aware) ─────────────────────────────────────────

interface MatRow { label: string; value: string; highlight?: boolean }

function buildMatRows(
  roomType: RoomType,
  sel: BuilderSelections,
  kitchen: KitchenSelections | null,
  bedroom: BedroomSelections | null,
): MatRow[] {
  if (roomType === "kitchen" && kitchen) {
    const sizeOpt     = KITCHEN_SIZE_OPTIONS.find((o) => o.id === kitchen.roomSize);
    const cabinetOpt  = kitchen.cabinetry  ? CABINETRY_OPTIONS.find((o)  => o.id === kitchen.cabinetry)  : null;
    const benchtopOpt = kitchen.benchtop   ? BENCHTOP_OPTIONS.find((o)   => o.id === kitchen.benchtop)   : null;
    const splashOpt   = kitchen.splashback ? SPLASHBACK_OPTIONS.find((o) => o.id === kitchen.splashback) : null;
    const mixerOpt    = kitchen.mixer      ? MIXER_OPTIONS.find((o)      => o.id === kitchen.mixer)      : null;
    const ceilingOpt  = CEILING_OPTIONS.find((o) => o.id === kitchen.ceilingStyle);
    const sizeLabel   = kitchen.roomSize === "custom" && kitchen.customLength > 0 && kitchen.customWidth > 0
      ? `Custom — ${kitchen.customLength}m × ${kitchen.customWidth}m (${(kitchen.customLength * kitchen.customWidth).toFixed(1)}m²)`
      : sizeOpt?.label ?? "Standard";

    const rows: MatRow[] = [
      { label: "Kitchen Size",     value: sizeLabel },
      { label: "Cabinetry Style",  value: cabinetOpt?.label  ?? "Not selected" },
      { label: "Benchtop",         value: benchtopOpt?.label ?? "Not selected" },
      { label: "Splashback",       value: splashOpt?.label   ?? "Not selected" },
      { label: "Mixer & Sink",     value: mixerOpt?.label    ?? "Not selected" },
      { label: "Cooktop",          value: kitchen.cooktop === "induction" ? "Induction" : "Gas" },
      { label: "Dishwasher",       value: kitchen.dishwasher === "integrated" ? "Integrated (panel-match)" : "Freestanding" },
      { label: "Ceiling Treatment",value: ceilingOpt?.label  ?? "Standard White" },
    ];
    if (kitchen.hasIsland)           rows.push({ label: "Island Bench",       value: "Included — plumbing/gas advisory applies", highlight: true });
    if (kitchen.hasApplianceRoughin) rows.push({ label: "Appliance Rough-ins",value: "New gas point or 15A circuit", highlight: true });
    if (kitchen.hasSinkRoughin)      rows.push({ label: "Sink Rough-in",      value: "Drain & water supply relocation", highlight: true });
    if (kitchen.hasWallChange)       rows.push({ label: "Wall Removal",        value: "Open-plan conversion — engineer required", highlight: true });
    if (kitchen.hasButlersPantry)    rows.push({ label: "Butler's Pantry",     value: "Integrated scullery with matching cabinetry" });
    if (kitchen.customNote?.trim())  rows.push({ label: "Client Request",      value: kitchen.customNote.trim() });
    return rows;
  }

  if (roomType === "bedroom" && bedroom) {
    const sizeOpt     = BEDROOM_SIZE_OPTIONS.find((o) => o.id === bedroom.roomSize);
    const flooringOpt = bedroom.flooring        ? BEDROOM_FLOORING_OPTIONS.find((o)  => o.id === bedroom.flooring)        : null;
    const wallOpt     = bedroom.wallTreatment   ? WALL_TREATMENT_OPTIONS.find((o)    => o.id === bedroom.wallTreatment)   : null;
    const lightOpt    = bedroom.lighting        ? BEDROOM_LIGHTING_OPTIONS.find((o)  => o.id === bedroom.lighting)        : null;
    const storageOpt  = bedroom.storage         ? STORAGE_OPTIONS.find((o)           => o.id === bedroom.storage)         : null;
    const windowOpt   = bedroom.windowTreatment ? WINDOW_TREATMENT_OPTIONS.find((o)  => o.id === bedroom.windowTreatment) : null;
    const ceilingOpt  = CEILING_OPTIONS.find((o) => o.id === bedroom.ceilingStyle);
    const sizeLabel   = bedroom.roomSize === "custom" && bedroom.customLength > 0 && bedroom.customWidth > 0
      ? `Custom — ${bedroom.customLength}m × ${bedroom.customWidth}m (${(bedroom.customLength * bedroom.customWidth).toFixed(1)}m²)`
      : sizeOpt?.label ?? "Master Bedroom";

    const rows: MatRow[] = [
      { label: "Room Size",         value: sizeLabel },
      { label: "Flooring",          value: flooringOpt?.label ?? "Not selected" },
      { label: "Wall Treatment",    value: wallOpt?.label     ?? "Not selected" },
      { label: "Lighting",          value: lightOpt?.label    ?? "Not selected" },
      { label: "Storage / Joinery", value: storageOpt?.label  ?? "Not selected" },
      { label: "Window Treatment",  value: windowOpt?.label   ?? "Not selected" },
      { label: "Ceiling Treatment", value: ceilingOpt?.label  ?? "Standard White" },
    ];
    if (bedroom.hasVJWall)         rows.push({ label: "VJ Feature Wall",    value: "Floor-to-ceiling tongue-and-groove boards" });
    if (bedroom.hasMediaJoinery)   rows.push({ label: "Media Joinery",      value: "Built-in TV unit with integrated shelving" });
    if (bedroom.hasPendantRoughin) rows.push({ label: "Pendant Rough-ins",  value: "New electrical circuit for bedside sconces", highlight: true });
    if (bedroom.customNote?.trim()) rows.push({ label: "Client Request",    value: bedroom.customNote.trim() });
    return rows;
  }

  // Bathroom
  const vanityLabel  = VANITY_OPTIONS.find((v)  => v.id === sel.vanity)?.label  ?? sel.vanity;
  const tapwareLabel = TAPWARE_OPTIONS.find((t)  => t.id === sel.tapware)?.label ?? sel.tapware;
  const rows: MatRow[] = [
    { label: "Floor Tile",    value: sel.floorTile?.name  ?? "Not selected" },
    { label: "Wall Tile",     value: sel.wallTile?.name   ?? "Not selected" },
    { label: "Vanity Type",   value: vanityLabel },
    { label: "Tapware Finish",value: tapwareLabel },
  ];
  if (sel.tileStyle)                                         rows.push({ label: "Tile Pattern",     value: sel.tileStyle });
  if (sel.lightingOption && sel.lightingOption !== "standard") rows.push({ label: "Lighting Upgrade", value: sel.lightingOption });
  if (sel.customNote?.trim())                                rows.push({ label: "Client Request",   value: sel.customNote.trim() });
  const sc = sel.structuralChanges;
  if (sc?.removeBathtub)   rows.push({ label: "Structural", value: "Bathtub removal",           highlight: true });
  if (sc?.addWalkinShower) rows.push({ label: "Structural", value: "Walk-in shower conversion",  highlight: true });
  if (sc?.replaceToilet)   rows.push({ label: "Structural", value: "Toilet replacement",         highlight: true });
  if (sc?.inWallCistern)   rows.push({ label: "Structural", value: "In-wall cistern",            highlight: true });
  return rows;
}

// ── Build cost items (room-aware) ────────────────────────────────────────────

interface CostItem { label: string; amount: number; detail?: string; warning?: boolean }

function buildCostItems(
  roomType: RoomType,
  sel: BuilderSelections,
  kitchen: KitchenSelections | null,
  bedroom: BedroomSelections | null,
): CostItem[] {
  if (roomType === "kitchen" && kitchen) {
    return calcKitchenCost(kitchen).items;
  }
  if (roomType === "bedroom" && bedroom) {
    return calcBedroomCost(bedroom).items;
  }
  // Bathroom
  const baseCost = getBathroomBaseCost(sel.bathroomSize, sel.customLength, sel.customWidth);
  return buildItemisedCosts(sel.floorTile, sel.wallTile, sel.vanity, sel.tapware, sel.structuralChanges, baseCost);
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function generateProReportPDF(input: ProReportInput): Promise<void> {
  const {
    selections, projectBrief, generatedImageUrl, roomPhotoUrl,
    grandTotal, estimatedCost, roomType, kitchenSelections, bedroomSelections,
  } = input;

  const pdf    = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW     = pdf.internal.pageSize.getWidth();   // 210mm
  const PH     = pdf.internal.pageSize.getHeight();  // 297mm
  const MARGIN = 13;
  const IW     = PW - MARGIN * 2;                    // inner width

  const rl = roomLabel(roomType);
  const dateStr = new Date().toLocaleDateString("en-AU", { year: "numeric", month: "long", day: "numeric" });

  const matRows   = buildMatRows(roomType, selections, kitchenSelections, bedroomSelections);
  const costItems = buildCostItems(roomType, selections, kitchenSelections, bedroomSelections);
  const briefItems = projectBrief ? calcBriefCostItems(projectBrief) : [];

  // Pre-load images
  const [aiImageData, roomImageData] = await Promise.all([
    generatedImageUrl ? loadImageAsDataUrl(generatedImageUrl) : Promise.resolve(null),
    roomPhotoUrl      ? loadImageAsDataUrl(roomPhotoUrl)      : Promise.resolve(null),
  ]);

  // ══════════════════════════════════════════════════════════════════
  //  PAGE 1 — Design Preview + Materials Specification
  // ══════════════════════════════════════════════════════════════════
  addHeader(pdf, PW, `${rl} Design Preview Report`, 1);
  let y = 22;

  // Title bar
  drawRect(pdf, MARGIN, y, 4, 7, TERRACOTTA, 2);
  sf(pdf, "bold");
  pdf.setTextColor(...CHARCOAL);
  pdf.setFontSize(13);
  pdf.text(`Your ${rl} Design Preview`, MARGIN + 7, y + 5.5);
  sf(pdf, "normal");
  pdf.setFontSize(7.5);
  pdf.setTextColor(...GREY_TEXT);
  pdf.text(`Prepared ${dateStr} · Reno Ready AI Design Platform`, MARGIN + 7, y + 12);
  y += 18;

  // Before / After images
  const imgH = 58;
  const imgW = (IW - 5) / 2;

  if (roomImageData) {
    pdf.addImage(roomImageData, "JPEG", MARGIN, y, imgW, imgH);
    drawRect(pdf, MARGIN, y + imgH - 7, imgW, 7, CHARCOAL);
    sf(pdf, "bold"); pdf.setFontSize(6.5); pdf.setTextColor(...WHITE);
    pdf.text("CURRENT STATE", MARGIN + imgW / 2, y + imgH - 2.5, { align: "center" });
  } else {
    drawRect(pdf, MARGIN, y, imgW, imgH, SAND, 3);
    sf(pdf, "normal"); pdf.setFontSize(7.5); pdf.setTextColor(...GREY_TEXT);
    pdf.text("No room photo uploaded", MARGIN + imgW / 2, y + imgH / 2, { align: "center" });
  }

  const rx = MARGIN + imgW + 5;
  if (aiImageData) {
    pdf.addImage(aiImageData, "JPEG", rx, y, imgW, imgH);
    drawRect(pdf, rx, y + imgH - 7, imgW, 7, TERRACOTTA);
    sf(pdf, "bold"); pdf.setFontSize(6.5); pdf.setTextColor(...WHITE);
    pdf.text("AI FUTURE VISION", rx + imgW / 2, y + imgH - 2.5, { align: "center" });
  } else {
    drawRect(pdf, rx, y, imgW, imgH, [230, 222, 212] as [number, number, number], 3);
    sf(pdf, "normal"); pdf.setFontSize(7.5); pdf.setTextColor(...GREY_TEXT);
    pdf.text("Generate an AI preview first", rx + imgW / 2, y + imgH / 2, { align: "center" });
  }
  y += imgH + 6;

  // Cost hero card
  const total = projectBrief ? grandTotal : estimatedCost;
  drawRect(pdf, MARGIN, y, IW, 20, CHARCOAL, 3);
  sf(pdf, "bold");
  pdf.setFontSize(6.5); pdf.setTextColor(180, 190, 200);
  pdf.text("ESTIMATED ALL-IN COST", MARGIN + 6, y + 6.5);
  pdf.setFontSize(17); pdf.setTextColor(...WHITE);
  pdf.text(formatAUD(Math.round(total / 500) * 500), MARGIN + 6, y + 16);
  sf(pdf, "normal");
  pdf.setFontSize(6.5); pdf.setTextColor(180, 190, 200);
  pdf.text(
    `Range: ${formatAUD(Math.round(total * 0.88 / 500) * 500)} – ${formatAUD(Math.round(total * 1.12 / 500) * 500)}  ·  QLD 2026 market rates  ·  ±12% variance`,
    PW - MARGIN - 3, y + 16, { align: "right" }
  );
  y += 26;

  // Materials specification table
  sf(pdf, "bold");
  pdf.setFontSize(9); pdf.setTextColor(...CHARCOAL);
  pdf.text("Materials & Specification", MARGIN, y + 4);
  y += 9;

  // Column header strip
  drawRect(pdf, MARGIN, y, IW, 6.5, CHARCOAL);
  sf(pdf, "bold"); pdf.setFontSize(6); pdf.setTextColor(...WHITE);
  pdf.text("ITEM", MARGIN + 3, y + 4.5);
  pdf.text("SPECIFICATION", MARGIN + 58, y + 4.5);
  y += 6.5;

  const rowH = 8.5;
  matRows.forEach((row, i) => {
    const bg = row.highlight
      ? [255, 251, 235] as [number, number, number]
      : i % 2 === 0 ? WHITE : LIGHT_SAND;
    drawRect(pdf, MARGIN, y, IW, rowH, bg);

    sf(pdf, "bold"); pdf.setFontSize(6.5);
    pdf.setTextColor(row.highlight ? AMBER[0] : GREY_TEXT[0], row.highlight ? AMBER[1] : GREY_TEXT[1], row.highlight ? AMBER[2] : GREY_TEXT[2]);
    pdf.text(row.label.toUpperCase(), MARGIN + 3, y + 5.8);

    sf(pdf, "normal"); pdf.setFontSize(7.5);
    pdf.setTextColor(...CHARCOAL);
    // Truncate long values to fit the column
    const maxW = IW - 62;
    const lines = pdf.splitTextToSize(row.value, maxW) as string[];
    pdf.text(lines[0], MARGIN + 58, y + 5.8);

    y += rowH;
  });

  addFooter(pdf, PW, PH);

  // ══════════════════════════════════════════════════════════════════
  //  PAGE 2 — Itemised Cost Breakdown + Project Brief
  // ══════════════════════════════════════════════════════════════════
  pdf.addPage();
  addHeader(pdf, PW, "Detailed Cost Breakdown", 2);
  y = 22;

  // Title
  drawRect(pdf, MARGIN, y, 4, 7, TERRACOTTA, 2);
  sf(pdf, "bold"); pdf.setFontSize(13); pdf.setTextColor(...CHARCOAL);
  pdf.text("Detailed Cost Breakdown", MARGIN + 7, y + 5.5);
  y += 13;

  // Column headers
  const labelX = MARGIN + 3;
  const detailX = MARGIN + 82;
  const amtX    = PW - MARGIN - 2;
  drawRect(pdf, MARGIN, y, IW, 6.5, CHARCOAL);
  sf(pdf, "bold"); pdf.setFontSize(6); pdf.setTextColor(...WHITE);
  pdf.text("ITEM", labelX, y + 4.5);
  pdf.text("DETAIL", detailX, y + 4.5);
  pdf.text("AMOUNT (INC. GST)", amtX, y + 4.5, { align: "right" });
  y += 6.5;

  // Cost line items
  const itemH = 9;
  costItems.forEach((item, i) => {
    const bg = item.warning
      ? [255, 251, 235] as [number, number, number]
      : i % 2 === 0 ? WHITE : LIGHT_SAND;
    drawRect(pdf, MARGIN, y, IW, itemH, bg);

    // Label
    sf(pdf, item.warning ? "bold" : "normal");
    pdf.setFontSize(7.5);
    const labelColor = item.warning ? AMBER : CHARCOAL;
    pdf.setTextColor(...labelColor);
    pdf.text(item.label, labelX, y + 6);

    // Detail
    if (item.detail) {
      sf(pdf, "normal"); pdf.setFontSize(6); pdf.setTextColor(...GREY_TEXT);
      const detailLines = pdf.splitTextToSize(item.detail, amtX - detailX - 18) as string[];
      pdf.text(detailLines[0], detailX, y + 6);
    }

    // Amount
    sf(pdf, "bold"); pdf.setFontSize(7.5);
    pdf.setTextColor(...(item.warning ? AMBER : CHARCOAL));
    const amtStr = item.amount > 0 ? `+${formatAUD(item.amount)}` : item.amount < 0 ? formatAUD(item.amount) : "Included";
    pdf.text(amtStr, amtX, y + 6, { align: "right" });

    y += itemH;
  });

  // Brief verified items (if any)
  if (briefItems.length > 0) {
    y += 2;
    drawRect(pdf, MARGIN, y, IW, 6.5, [235, 230, 224] as [number, number, number]);
    sf(pdf, "bold"); pdf.setFontSize(5.5); pdf.setTextColor(...GREY_TEXT);
    pdf.text("VERIFIED COST ITEMS  ·  SOURCED FROM REAL AUSTRALIAN INVOICES", labelX, y + 4.5);
    y += 6.5;

    briefItems.forEach((item, i) => {
      const bg = i % 2 === 0 ? WHITE : [255, 251, 235] as [number, number, number];
      drawRect(pdf, MARGIN, y, IW, itemH, bg);
      sf(pdf, "normal"); pdf.setFontSize(7.5);
      pdf.setTextColor(item.warning ? AMBER[0] : CHARCOAL[0], item.warning ? AMBER[1] : CHARCOAL[1], item.warning ? AMBER[2] : CHARCOAL[2]);
      pdf.text(`${item.warning ? "⚠  " : ""}${item.label}`, labelX, y + 6);
      sf(pdf, "bold"); pdf.setFontSize(7.5);
      pdf.text(`+${formatAUD(item.amount)}`, amtX, y + 6, { align: "right" });
      y += itemH;
    });
  }

  // Grand total row
  y += 2;
  drawRect(pdf, MARGIN, y, IW, 11, CHARCOAL, 3);
  sf(pdf, "bold"); pdf.setFontSize(8.5); pdf.setTextColor(...WHITE);
  pdf.text("ALL-IN ESTIMATED TOTAL", labelX, y + 7.5);
  pdf.text(formatAUD(Math.round(total / 500) * 500), amtX, y + 7.5, { align: "right" });
  y += 15;

  // Variance note
  sf(pdf, "normal"); pdf.setFontSize(7); pdf.setTextColor(...GREY_TEXT);
  pdf.text(
    `Typical range: ${formatAUD(Math.round(total * 0.88 / 500) * 500)} – ${formatAUD(Math.round(total * 1.12 / 500) * 500)}  (±12% variance based on site conditions and trade availability)`,
    labelX, y
  );
  y += 8;

  // Single-bathroom hygiene advisory
  if (roomType === "bathroom" && projectBrief?.bathroomCount === 1) {
    drawRect(pdf, MARGIN, y, IW, 22, [255, 251, 235] as [number, number, number], 3);
    sf(pdf, "bold"); pdf.setFontSize(6.5); pdf.setTextColor(...AMBER);
    pdf.text("⚠  SINGLE BATHROOM — HYGIENE ADVISORY", labelX, y + 6);
    sf(pdf, "normal"); pdf.setFontSize(7.5); pdf.setTextColor(...CHARCOAL);
    const hygText = pdf.splitTextToSize(
      "This is the only bathroom in the home. Most clients arrange a Mobile Ensuite (self-contained trailer) for $150–$300/week during the 2–4 week build. Confirm toilet and shower access with your builder before works commence.",
      IW - 6
    ) as string[];
    hygText.slice(0, 3).forEach((l: string, li: number) => pdf.text(l, labelX, y + 12 + li * 4.8));
    y += 28;
  }

  // Project Brief summary box
  if (projectBrief) {
    y += 2;
    const briefLines = [
      `Year of Construction: ${projectBrief.yearBuilt ?? "Unknown"}`,
      `Renovation Scope: ${projectBrief.scope === "full-stripout" ? "Full Strip-out & Rebuild" : "Cosmetic Refresh"}`,
      `Plumbing: ${projectBrief.plumbingLayout === "keep-layout" ? "Keeping existing layout" : "Moving plumbing / walls"}`,
      `Bathrooms in home: ${projectBrief.bathroomCount === 3 ? "3 or more" : String(projectBrief.bathroomCount)}${projectBrief.bathroomCount === 1 ? " (sole bathroom — access plan required)" : ""}`,
      ...(needsAsbestosCheck(projectBrief) ? ["⚠  Asbestos risk flagged — testing & removal included in estimate above"] : []),
    ];
    const briefH = 9 + briefLines.length * 5.2;
    drawRect(pdf, MARGIN, y, IW, briefH, SAND, 3);
    sf(pdf, "bold"); pdf.setFontSize(6.5); pdf.setTextColor(...TERRACOTTA);
    pdf.text("PROJECT BRIEF SUMMARY", labelX, y + 6.5);
    sf(pdf, "normal"); pdf.setFontSize(7.5); pdf.setTextColor(...CHARCOAL);
    briefLines.forEach((line, li) => pdf.text(line, labelX, y + 12 + li * 5.2));
    y += briefH + 4;
  }

  // Disclaimer block
  y = Math.max(y, PH - 35);
  drawRect(pdf, MARGIN, y, IW, 20, LIGHT_SAND, 3);
  sf(pdf, "bold"); pdf.setFontSize(6); pdf.setTextColor(...GREY_TEXT);
  pdf.text("IMPORTANT DISCLAIMER", labelX, y + 5.5);
  sf(pdf, "normal"); pdf.setFontSize(6.5); pdf.setTextColor(...GREY_TEXT);
  const discText = pdf.splitTextToSize(
    "This report is a planning aid only. All cost estimates are indicative and based on mid-range QLD 2026 trade rates. Actual costs may vary significantly depending on site conditions, materials availability, trade access, and scope changes. Always obtain at least two written quotes from licensed builders before proceeding. Reno Ready accepts no liability for cost variations.",
    IW - 6
  ) as string[];
  discText.slice(0, 3).forEach((l: string, li: number) => pdf.text(l, labelX, y + 10 + li * 4.2));

  addFooter(pdf, PW, PH);

  pdf.save("Reno-Ready-Pro-Report.pdf");
}
